### ISSUE TITLE
Replace default favicon and metadata with Virufy logo and metadata

### ISSUE THREAD

**Issue by gevuong** [gevuong/minimal-i18n-with-app-router#2]
Currently, the Next.js logo is being used. We would like to replace that with the Virufy logo. Logo will primarily be seen in the browser tab. Metadata should also be updated, as it currently states, "Create Next App" in the browser tab.

**Comment by ridham-virufy** [comment]
I have reached out to sherie for the virufy logo with 256 * 256 px size, Will update once I hear from her. 

For the Dynamic tab names I will need to add [this](https://github.com/virufy4/virufy4.github.io/blob/f98d4b8e5d9f508867575294fdbaa2ae54e82495/src/components/SEO.jsx) file from 4.0 to this repo. I haven't worked a lot on this repo so can you help me figure out where the location of this should be? @gevuong

**Comment by gevuong** [comment]
I found the Virufy logo in virufy4 and updated the metadata 👍🏼
