### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by gevuong** [gevuong/minimal-i18n-with-app-router#24]

**Comment by ridham-virufy** [comment]
How far do you want me to go in terms of documentation? I think Xin Shu and Anusha are working on documenting the repo. Like virufy6.0 I can have them lead here and I can answer any necessary questions they might have.

**Comment by gevuong** [comment]
iirc you worked with Steven on documentation in Confluence. Can you share link to it? I'd like to get a better understanding of its content so far so we don't duplicate work.

**Comment by ridham-virufy** [comment]
Here is the [Confluence Page](https://virufy.atlassian.net/wiki/spaces/VIRUFY/pages/239108105/Mapping+GitHub+Code+to+Website+6.0
)

**Comment by ridham-virufy** [comment]
Quick update: I haven't heard back from Anusha to Xin about documentation. I did double slack now so lets wait.

**Comment by gevuong** [comment]
Ok no worries and thanks for the update. I plan to add some content in the README on Wed.
