### ISSUE TITLE
Clicking on "Cookie Settings" in footer opens an accordion with no content

### ISSUE THREAD

**Issue by gevuong** [gevuong/minimal-i18n-with-app-router#25]
Double check w/ Gabriela and team if content displayed after clicking on the following 4 links are up-to-date:

- [Cookie Policy](https://gevuong.github.io/minimal-i18n-with-app-router/en/covid19#)
- [Cookie Settings](https://gevuong.github.io/minimal-i18n-with-app-router/en/covid19#)
- [Privacy Policy](https://gevuong.github.io/minimal-i18n-with-app-router/en/covid19#)
- [Do Not Sell My Personal Information](https://gevuong.github.io/minimal-i18n-with-app-router/en/covid19#)

I noticed that clicking on Cookie Settings renders what I believe is part of an accordion. The content is not visible.

**Comment by ridham-virufy** [comment]
I have reached out to Sherrie. Waiting on her reply.

**Comment by ridham-virufy** [comment]
Quick Update: Sherrie is not aware of the info we want, I have reached out to Deepika if she has any input on this.

**Comment by gevuong** [comment]
Ok. I would also reach out to Gabriela. She usually manages what content should be on the site and then shares it with the designers.
