### ISSUE TITLE
update content in supporters, one young world, faq, join team, and diseases pages (assigned to Naysha)

### ISSUE THREAD

**Issue by gevuong** [gevuong/minimal-i18n-with-app-router#35]
Rupak has updated content for the first 5 pages. Use this google doc to update content in the remaining 5 pages: 
- supporters
- one young world
- faq
- join team
- diseases

https://docs.google.com/document/d/1isZiE1mJKFrgvvVvrW5qFeaQ5LkImQ2QB671ezzeFrs/edit?hl=en

**Comment by gevuong** [comment]
@nayshajain is this issue complete? Or are there more changes needed?

**Comment by nayshajain** [comment]
This is complete for now. :)
