### ISSUE TITLE
update profile pictures of advisors

### ISSUE THREAD

**Issue by gevuong** [gevuong/minimal-i18n-with-app-router#4]
Profile pictures of advisors need to be updated and added.

Refer to these Slack message for more info: 
- https://virufy.slack.com/archives/C076DU42PRQ/p1717048870367069
- https://virufy.slack.com/archives/C076DU42PRQ/p1717739274324969

**Comment by ridham-virufy** [comment]
https://docs.google.com/spreadsheets/d/1u8zbo3liGU2PmyNAAwRjrxyEEprPOFnlXlyIy0ylgCc/edit?gid=0#gid=0

Here is the spreadsheet Sheerie shared!

**Comment by gevuong** [comment]
For context, these are the notes left by Gabriela today:

```
I contacted Frederick Cosper and here is the answer: use current advisors already on Virufy website 4.0.
```

For more info, scroll to bottom of google docs:
https://docs.google.com/document/d/1isZiE1mJKFrgvvVvrW5qFeaQ5LkImQ2QB671ezzeFrs/edit?hl=en
