### ISSUE TITLE
Update advisors in `/people` page

### ISSUE THREAD

**Issue by gevuong** [gevuong/minimal-i18n-with-app-router#63]
Per Amil's request,

- [x] "remove Anais and Richard S and Mathjis from advisors page!"
- [x] "Please keep the new website advisors page the same as what we have currently:
[https://virufy.org/en/team/](https://www.google.com/url?q=https://virufy.org/en/team/&sa=D&source=editors&ust=1726785498843754&usg=AOvVaw3PY756SOjuc49Za9pOy1Ij)"
- [x] regarding where to find the photos to replace the old and blurry ones, "copy from our current website: [https://virufy.org/en/team/](https://www.google.com/url?q=https://virufy.org/en/team/&sa=D&source=editors&ust=1726785498844556&usg=AOvVaw1g0bsaokXAHNR28pHGePMn)"
- [x] Add May Xu
- [x] There should be 25 advisors, similar to virufy4.

Awaiting response from marketing + design:
- [ ] Should ordering resemble virufy4 or Figma design?

**Comment by a-wong-8** [comment]
I added may xu, removed george pegelow, rich walcoff, pedro siena, and taisuke fukuno.
