### ISSUE TITLE
Update content in home `/` page

### ISSUE THREAD

**Issue by gevuong** [gevuong/minimal-i18n-with-app-router#76]
Based on Amil's feedback, there are issues that need to be addressed in the home page:
https://gevuong.github.io/minimal-i18n-with-app-router

- [ ] Can't read "Your Digital Health Companion" on home page as the font is the same color as the waveform.
- [ ] Text is not centered on home page: "Introducing Virufy, the cutting-edge app that ..." Some weird line breaks happeneing
- [ ] Remove "Empower yourself with the latest in health technology." on home page, not adding value
- [ ] "*The app is still under development, support us by contributing your data into our data collection app." => "*The app is still under development, support us by contributing your cough sounds into our data collection app."
- [ ] "Receive immediate prompt feedback on your cough's characteristics and abnormality profile based on the sound pattern of your cough*" =>"Rapid feedback on your cough's characteristics and abnormality profile based on the sound pattern of your cough"
- [ ] Increase font size of "*The results of the analysis done by the system will not replace the diagnosis by a specialized doctor." and replace to say "Virufy will not take place of a doctor and would like to remind you it is your responsibility to seek medical advice from your doctor."
- [ ] Replace "Artificial Intelligence (AI) is capable of detecting tiny differences in vocal patterns to detect disease presence." = > "Artificial Intelligence (AI) is capable of detecting minute differences in vocal patterns to detect disease presence."
- [ ] Increase font size "Our groundbreaking app employs cutting-edge AI technology to analyze your breathing patterns using deep learning algorithms and audio signal processing techniques."

Some of these issues may need to be discussed with design team in order to progress.
For example, what the color of "Your Digital Health Companion" should be.

Lmk if you have any questions.

**Comment by devfercastro** [comment]
Hi, want some help of mine?

**Comment by devfercastro** [comment]
The changes in text I can do it for both English and Spanish, for the rest I'm going to use genAI.
[] Can't read "Your Digital Health Companion" on home page as the font is the same color as the waveform.
- What about a white text with a `text-shadow: 3px 3px 5px #33B49B`
[] Text is not centered on home page: "Introducing Virufy, the cutting-edge app that ..." Some weird line breaks happeneing
- No problem
[] Remove "Empower yourself with the latest in health technology." on home page, not adding value
- No problem
[] "*The app is still under development, support us by contributing your data into our data collection app." => "*The app is still under development, support us by contributing your cough sounds into our data collection app."
- No problem
[] "Receive immediate prompt feedback on your cough's characteristics and abnormality profile based on the sound pattern of your cough*" =>"Rapid feedback on your cough's characteristics and abnormality profile based on the sound pattern of your cough"
- No problem
[] Increase font size of "*The results of the analysis done by the system will not replace the diagnosis by a specialized doctor." and replace to say "Virufy will not take place of a doctor and would like to remind you it is your responsibility to seek medical advice from your doctor."
- Make sense for small displays, it would be better `text-[0.6rem] leading-[0.8rem]`.
[] Replace "Artificial Intelligence (AI) is capable of detecting tiny differences in vocal patterns to detect disease presence." = > "Artificial Intelligence (AI) is capable of detecting minute differences in vocal patterns to detect disease presence."
No problem.
[] Increase font size "Our groundbreaking app employs cutting-edge AI technology to analyze your breathing patterns using deep learning algorithms and audio signal processing techniques."
No problem, I'll do it for 01 and 02.

*Does this sounds good for you?*

**Comment by gevuong** [comment]
@devfercastro Hi, sure!  The scope of this issue will only be for the English translation.

I reached out to design team to ask what font color and size to use for the following issues.

- [ ] Can't read "Your Digital Health Companion" on home page as the font is the same color as the waveform.
- [ ] Increase font size "Our groundbreaking app employs cutting-edge AI technology to analyze your breathing patterns using deep learning algorithms and audio signal processing techniques."

In the mean time, feel free to work on the remaining issues.

**Comment by devfercastro** [comment]
Thanks. Also I'm a native Spanish speaker if you need help with that language update the tasks of this issue or assign me to a new one.
