### ISSUE TITLE
Add Nexus Tax Services logo

### ISSUE THREAD

**Issue by gevuong** [gevuong/minimal-i18n-with-app-router#83]
For reference, the logo has already been added to 4.0: https://virufy.org/en/oursupporters#

Status: 
- [ ] Waiting for Figma design and logo (preferably in white text). Provided logo has black text, which does not adhere to the other logo on the [/supporters](https://gevuong.github.io/minimal-i18n-with-app-router/en/supporters) page.

**Comment by gevuong** [comment]
For context, I cc'd the design team 10 days ago but haven't heard back. I just followed up with them earlier today.

This is the logo provided by company. Based on the design of all the logos and background color in the supporters page, I assume the black and blue colors should be white.

![Nexus_Tax_Services (Noback) (1)](https://github.com/user-attachments/assets/50bcddd2-68c0-4f03-8c78-1c9b38b4678e)

**Comment by a-wong-8** [comment]
![Nexus_Tax_Services-200px](https://github.com/user-attachments/assets/a9a0e797-bca1-4648-8f17-def87dc0c437)

**Comment by a-wong-8** [comment]
![Screenshot 2024-10-20 152634](https://github.com/user-attachments/assets/6288cd2b-d746-4d44-8c94-5257f40943ef)

**Comment by a-wong-8** [comment]
![Screenshot 2024-10-20 at 3 39 24 PM](https://github.com/user-attachments/assets/7a3fe995-4222-46e5-95d0-b789eaf51ce4)

**Comment by a-wong-8** [comment]
![Screenshot 2024-10-20 at 3 47 09 PM](https://github.com/user-attachments/assets/f3e014e0-15e6-4318-b703-59fdf7ae7406)
