### ISSUE TITLE
replace English text with Japanese translations

### ISSUE THREAD

**Issue by gevuong** [gevuong/minimal-i18n-with-app-router#89]
When `JA` locale is selected,
- [x] Replace 'Donate Options' in donate modal with `寄付オプション`.
- [x] Replace 'Join our Team' in `/one-young-world` with `チームに参加する`.
- [x] Implement proposed translation changes listed in [Google sheets](https://docs.google.com/spreadsheets/d/1u2GZ-hwEp8EmsxKchg9VrCP67Xwhdz2eeEXoXe4saw8/edit?gid=0#gid=0).

**Comment by a-wong-8** [comment]
what about "Apply to this role" in JobDetailPage?

**Comment by gevuong** [comment]
Yeah, good catch. That will be be updated as well.
After review from the Japan team, there's a decent amount of content that needs to be translated or re-translated.
